# Generated by Django 5.2.4 on 2025-08-24 21:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_product_codes', related_query_name='pharmacy_product_codes', to='accounts.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_product_codes', related_query_name='pharmacy_product_codes', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='accounts.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.product')),
                ('product_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', related_query_name='offers', to='store.pharmacyproductcode')),
            ],
        ),
        migrations.AddIndex(
            model_name='pharmacyproductcode',
            index=models.Index(fields=['product', 'pharmacy'], name='store_pharm_product_8b3989_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyproductcode',
            index=models.Index(fields=['product'], name='store_pharm_product_37cd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyproductcode',
            index=models.Index(fields=['pharmacy'], name='store_pharm_pharmac_99e551_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacyproductcode',
            unique_together={('product', 'pharmacy', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('pharmacy', 'product')},
        ),
    ]
