# Generated by Django 5.2.4 on 2025-08-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('offer_type', models.CharField(choices=[('PERCENTAGE', 'خصم بنسبة مئوية'), ('BOGO', 'اشترِ واحدة واحصل على واحدة مجانًا'), ('SECOND_HALF', 'اشترِ واحدة واحصل على الثانية بنصف السعر')], default='PERCENTAGE', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
